services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/certs:/etc/nginx/certs  
    depends_on:
      - backend
      - frontend
  backend:
    build: ./backend
    volumes:
      - ./backend:/app  
    environment:
      - FLASK_ENV=development  
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app  
  redis:
    image: redis:alpine
