services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/certs:/etc/nginx/certs  
    depends_on:
      - backend
      - frontend
  backend:
    build: ./backend
    volumes:
      - ./backend:/app  
    environment:
      - RATELIMIT_STORAGE_URL=redis://redis:6379/0
      - FLASK_ENV=development
    depends_on:
      - redis
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app  
  redis:
    image: redis:alpine
    ports:
    - "6379:6379"
